server:
  port: 8081

spring:
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: none
  datasource:
    url: jdbc:mysql://localhost:3306/sakila?useSSl=false&serverTimeZone=UTC
    username: XXXXXXXX
    password: XXXXXXXX
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name : SpringBootJPAHikariCP
      connection-timeout: 2000
      maximum-pool-size: 50
      minimum-idle: 10
      idle-timeout: 30000
      max-lifetime: 40000

logging:
  level:
    root: INFO

timeout: 5000

redis:
  port: 8083
  host: https://localhost:8083
  password: XXXXXXXX
  cachingTime: 5